name: Release
on:
  push:
    branches: ["main"]
    paths: ["CHANGELOG.md"]

  workflow_dispatch:


permissions:
  contents: write
#   releases: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry 
          poetry install
      - name: Run Test 
        run: |
          poetry run coverage run -m pytest
          poetry run coverage xml
      - name: Read changelog
        id: changelog
        run: |
          VERSION=$(head -n1 <(sed -n 's/^## \[\([^]]*\)\].*$/\1/p' CHANGELOG.md)) 
          echo "VERSION=$VERSION"   
          echo "::set-output name=version::$VERSION"
      - name: Update version in __init__.py file
        run: sed -i "s/{{version}}/$(grep -m1 -oP '^## \[\K[^\]]+' CHANGELOG.md | cut -d']' -f1)/g" py_selenium_declarative/__init__.py
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.version }}
          release_name: Release ${{ steps.changelog.outputs.version }}
          draft: false
          prerelease: true
