name: Release
on:
  push:
    branches: ["main"]
    paths: ["CHANGELOG.md"]

  workflow_dispatch:


permissions:
  contents: write
#   releases: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry 
          poetry install
      - name: Run Test 
        run: |
          poetry run coverage run -m pytest
          poetry run coverage xml
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml
          retention-days: 5
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.version }}
          release_name: Release ${{ steps.changelog.outputs.version }}
          draft: false
          prerelease: true
