name: Release
on:
  push:
    branches: ["main"]
    paths: ["CHANGELOG.md"]

  workflow_dispatch:


permissions:
  contents: read
  releases: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read changelog
        id: changelog
        run: |
          VERSION=$(head -n1 <(sed -n 's/^## \[\([^]]*\)\].*$/\1/p' CHANGELOG.md)) 
          echo "VERSION=$VERSION"   
          echo "::set-output name=version::$VERSION"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.version }}
          release_name: Release ${{ steps.changelog.outputs.version }}
          draft: false
          prerelease: false
